version: '3.8'

services:
  backend:
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shopdb
      SPRING_DATASOURCE_USERNAME: shopuser
      SPRING_DATASOURCE_PASSWORD: shoppass123
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PASSWORD: redispass
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: shopuser
      SPRING_RABBITMQ_PASSWORD: rabbitpass
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
    ports:
      - "8080:8080"
    # Без depends_on - приложение должно само ждать и переподключаться

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: shopdb
      POSTGRES_USER: shopuser
      POSTGRES_PASSWORD: shoppass123
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass redispass
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: shopuser
      RABBITMQ_DEFAULT_PASS: rabbitpass
    ports:
      - "5672:5672"
      - "15672:15672"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
