apiVersion: v1
kind: ConfigMap
metadata:
  name: task3-app-config
  namespace: task3
data:
  API_BASE_URL: /api
  POSTGRES_HOST: postgres-db
  POSTGRES_PORT: "5432"
  POSTGRES_DB: task3db
  POSTGRES_USER: task3user
