apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: task3-gateway
  namespace: task3
spec:
  gatewayClassName: nginx
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: task3-route
  namespace: task3
spec:
  parentRefs:
    - name: task3-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - name: task3-backend
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: task3-frontend
          port: 80
