apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task4.cnpgAppSecretName" . }}
  labels:
    {{- include "task4.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.cnpg.user | quote }}
  password: {{ .Values.cnpg.password | quote }}
