apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "task4.configMapName" . }}
  labels:
    {{- include "task4.labels" . | nindent 4 }}
data:
  API_BASE_URL: {{ .Values.frontend.apiBaseUrl | quote }}
  POSTGRES_HOST: {{ printf "%s-rw" (include "task4.cnpgClusterName" .) | quote }}
  POSTGRES_PORT: "5432"
  POSTGRES_DB: {{ .Values.cnpg.database | quote }}
